output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               about.html,\
               about_files/,\
               OSGI-INF/shadow.xml,\
               OSGI-INF/shadow_example.xml
src.includes = about.html,\
               about_files/
source.. = src/main/java/
additional.bundles = org.eclipse.osgi,\
                     org.eclipse.osgi.services,\
                     org.eclipse.osgi.util,\
                     org.eclipse.kura.api,\
                     slf4j.api
