openapi: 3.0.1
info:
  title: Example Service interface
  description: This is an Remote service rest interface
  version: 1.0.0
paths:
  /ping:
    get:
      responses:
        '200':
          description: "Returns a constant string"
          content:
            application/json:
              schema:
                type: string
  /sum:
    post:
      requestBody:
        description: "Performs the sum of two integers"
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: number
                b:
                  type: number
      responses:
        '200':
          description: "The sum result"
          content:
            application/json:
              schema:
                type: number
        

        
      